name: Update rusEFI Reference

on:
  schedule:
    - cron: '5 17 * * *' # update rusEFI reference daily at 5:05 pm
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: kifir23917/rusefi/.github/workflows/custom-board-update-rusefi-reference.yaml@lts-custom-software-daily-releases
    permissions:
      contents: write
